version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./app/YtManagerApp/static:/www/static
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    env_file:
      - sqlite3.env.env
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./media:/usr/src/app/data/media
      - ./db:/usr/src/app/data/db
    depends_on:
      - db
