# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ytid', models.TextField()),
                ('downloaded_path', models.TextField(null=True)),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='url',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='YtManagerApp.SubscriptionFolder'),
        ),
        migrations.AlterField(
            model_name='subscriptionfolder',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='YtManagerApp.SubscriptionFolder'),
        ),
        migrations.AddField(
            model_name='video',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YtManagerApp.Subscription'),
        ),
    ]
