# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0002_auto_20181003_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='YtManagerApp.SubscriptionFolder'),
        ),
        migrations.AlterField(
            model_name='subscriptionfolder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YtManagerApp.SubscriptionFolder'),
        ),
    ]
