# Generated by Django 2.1.2 on 2018-10-26 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0004_auto_20181014_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionfolder',
            options={'ordering': [django.db.models.functions.text.Lower('parent__name'), django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='auto_download',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='download_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='download_order',
            field=models.CharField(blank=True, choices=[('newest', 'Newest'), ('oldest', 'Oldest'), ('playlist', 'Playlist order'), ('playlist_reverse', 'Reverse playlist order'), ('popularity', 'Popularity'), ('rating', 'Top rated')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='icon_best',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='icon_default',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='manager_delete_after_watched',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YtManagerApp.SubscriptionFolder'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='playlist_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='auto_download',
            field=models.BooleanField(blank=True, help_text='Enables or disables automatic downloading.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='delete_watched',
            field=models.BooleanField(blank=True, help_text='Videos marked as watched are automatically deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_autogenerated_subtitles',
            field=models.BooleanField(blank=True, help_text='Enables downloading the automatically generated subtitle. The flag is passed directly to youtube-dl. You can find more information <a href="https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options">here</a>.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_file_pattern',
            field=models.CharField(blank=True, help_text='A pattern which describes how downloaded files are organized. Extensions are automatically appended. You can use the following fields, using the <code>${field}</code> syntax: channel, channel_id, playlist, playlist_id, playlist_index, title, id. Example: <code>${channel}/${playlist}/S01E${playlist_index} - ${title} [${id}]</code>', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_format',
            field=models.CharField(blank=True, help_text='Download format that will be passed to youtube-dl.  See the <a href="https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection"> youtube-dl documentation</a> for more details.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_global_limit',
            field=models.IntegerField(blank=True, help_text='Limits the total number of videos downloaded (-1 = no limit).', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_order',
            field=models.CharField(blank=True, choices=[('newest', 'Newest'), ('oldest', 'Oldest'), ('playlist', 'Playlist order'), ('playlist_reverse', 'Reverse playlist order'), ('popularity', 'Popularity'), ('rating', 'Top rated')], help_text='The order in which videos will be downloaded.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_path',
            field=models.CharField(blank=True, help_text='Path on the disk where downloaded videos are stored.  You can use environment variables using syntax: <code>${env:...}</code>', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_subscription_limit',
            field=models.IntegerField(blank=True, help_text='Limits the number of videos downloaded per subscription (-1 = no limit).  This setting can be overriden for each individual subscription in the subscription edit dialog.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_subtitles',
            field=models.BooleanField(blank=True, help_text='Enable downloading subtitles for the videos. The flag is passed directly to youtube-dl. You can find more information <a href="https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options">here</a>.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_subtitles_all',
            field=models.BooleanField(blank=True, help_text='If enabled, all the subtitles in all the available languages will be downloaded. The flag is passed directly to youtube-dl. You can find more information <a href="https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options">here</a>.', null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_subtitles_format',
            field=models.CharField(blank=True, help_text='Subtitles format preference. Examples: srt/ass/best The flag is passed directly to youtube-dl. You can find more information <a href="https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options">here</a>.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='download_subtitles_langs',
            field=models.CharField(blank=True, help_text='Comma separated list of languages for which subtitles will be downloaded. The flag is passed directly to youtube-dl. You can find more information <a href="https://github.com/rg3/youtube-dl/blob/master/README.md#subtitle-options">here</a>.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='mark_deleted_as_watched',
            field=models.BooleanField(blank=True, help_text="When a downloaded video is deleted from the system, it will be marked as 'watched'.", null=True),
        ),
    ]
