# Generated by Django 2.1.2 on 2018-10-07 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0005_auto_20181007_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='ytid',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='icon_best',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='icon_default',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='playlist_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
