# Generated by Django 2.1.2 on 2018-10-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0006_auto_20181008_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='downloader_enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='downloader_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='downloader_order',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='manager_delete_after_watched',
            field=models.BooleanField(null=True),
        ),
    ]
