# Generated by Django 2.1.2 on 2018-10-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0003_auto_20181013_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfolder',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
