# Generated by Django 2.1.2 on 2018-10-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0005_auto_20181026_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='manager_delete_after_watched',
            new_name='delete_after_watched',
        ),
    ]
