# Generated by Django 2.1.2 on 2018-10-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0006_auto_20181027_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='channel',
        ),
        migrations.AddField(
            model_name='subscription',
            name='channel_id',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='channel_name',
            field=models.CharField(default='Unknown', max_length=1024),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
