# Generated by Django 2.1.2 on 2018-12-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0007_auto_20181029_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='delete_after_watched',
            new_name='automatically_delete_watched',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
