# Generated by Django 2.2.4 on 2019-08-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0010_auto_20190819_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='icon_default',
        ),
        migrations.RemoveField(
            model_name='video',
            name='icon_default',
        ),
    ]
