# Generated by Django 2.2.4 on 2019-08-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0011_auto_20190819_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='icon_best',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='icon_best',
            new_name='thumbnail',
        ),
    ]
