# Generated by Django 3.0.4 on 2020-04-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0012_auto_20190819_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProviderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(help_text='Provider ID', max_length=128, unique=True)),
                ('settings', models.TextField(help_text='Video provider settings')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_id',
            field=models.CharField(default='YtAPI', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='downloaded_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.TextField(),
        ),
    ]
