# Generated by Django 2.2.5 on 2019-11-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YtManagerApp', '0012_auto_20190819_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_synchronised',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
